import sqlite3
c=sqlite3.connect('data/xop_trader.db')
cur=c.cursor()
print("=== Last 50 fills (trade_log) ===")
cur.execute("SELECT timestamp, pair_name, side, price_mojos, size_mojos, block_height FROM trade_log ORDER BY id DESC LIMIT 50")
for r in cur.fetchall(): print(r)
print()
print("=== Fills per pair/side last 7d (trade_log by created_at) ===")
cur.execute("SELECT pair_name, side, COUNT(*) FROM trade_log WHERE created_at > datetime('now','-7 days') GROUP BY pair_name, side ORDER BY 3 DESC")
for r in cur.fetchall(): print(r)
print()
print("=== Offer status last 7d ===")
cur.execute("SELECT pair_name, side, status, COUNT(*) FROM offer_log WHERE created_at > datetime('now','-7 days') GROUP BY pair_name, side, status ORDER BY pair_name, side, 4 DESC")
for r in cur.fetchall(): print(r)
print()
print("=== Cancel reasons last 7d ===")
cur.execute("SELECT cancel_reason, COUNT(*) FROM offer_log WHERE created_at > datetime('now','-7 days') AND status='cancelled' GROUP BY cancel_reason ORDER BY 2 DESC")
for r in cur.fetchall(): print(r)
print()
print("=== Avg competitiveness/exec_quality by pair/side last 7d ===")
cur.execute("SELECT pair_name, side, ROUND(AVG(competitiveness_score),2), ROUND(AVG(execution_quality_score),2), ROUND(AVG(queue_ahead_score),2), COUNT(*) FROM offer_log WHERE created_at > datetime('now','-7 days') GROUP BY pair_name, side")
for r in cur.fetchall(): print(r)
