"""QSS theme system with CHIA blockchain branding.

Provides a dark-mode colour palette, a complete Qt Style Sheet
covering every standard widget class, and helper functions to
apply the theme to any QApplication instance.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from PySide6.QtGui import QFont, QFontDatabase
from PySide6.QtWidgets import QApplication


# ---------------------------------------------------------------------------
# Colour palette -- official CHIA branding + trading-UI accents
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class ChiaColors:
    """Immutable container for every colour token used by the theme.

    Colour values are CSS hex strings suitable for direct
    interpolation into QSS rules.
    """

    # Brand greens
    PRIMARY_GREEN: str = "#3AAC59"
    LIGHT_GREEN: str = "#5ECE71"

    # Surface / background hierarchy (darkest -> lightest)
    DARK_BG: str = "#0D1117"
    PANEL_BG: str = "#161B22"
    ELEVATED_BG: str = "#1A2332"

    # Borders
    BORDER: str = "#2A2E39"

    # Typography
    TEXT_PRIMARY: str = "#E1E4E8"
    TEXT_SECONDARY: str = "#9CA3AF"  # Brightened for WCAG AA 4.5:1 on DARK_BG

    # Semantic / trading
    PROFIT_GREEN: str = "#3AAC59"
    LOSS_RED: str = "#EF5350"
    WARNING_YELLOW: str = "#F59E0B"
    INFO_BLUE: str = "#3B82F6"


# Module-level singleton so callers can import colours directly.
COLORS = ChiaColors()


# ---------------------------------------------------------------------------
# Font configuration
# ---------------------------------------------------------------------------

# Preferred monospaced font for numeric / data display.
MONO_FONT_FAMILY: str = "JetBrains Mono"

# Preferred proportional font for general UI text.
UI_FONT_FAMILY: str = "Inter"

# Fallback stack when preferred fonts are unavailable.
_MONO_FALLBACK: str = "'JetBrains Mono', 'Fira Code', 'Consolas', monospace"
_UI_FALLBACK: str = "'Inter', 'Segoe UI', 'Helvetica Neue', sans-serif"

# Base sizes (points).  Adjusted by *font_size_delta* at runtime.
_BASE_UI_FONT_SIZE: int = 10
_BASE_MONO_FONT_SIZE: int = 10


def _resolve_font(family: str, fallback: str, size_pt: int) -> QFont:
    """Build a QFont, falling back through the stack when *family* is absent.

    Parameters
    ----------
    family:
        First-choice font family name.
    fallback:
        Comma-separated CSS-style fallback list (used only for QSS;
        QFont itself resolves via Qt font matching).
    size_pt:
        Point size.

    Returns
    -------
    QFont configured with the best available family.
    """
    font = QFont(family, size_pt)
    # If Qt substituted because *family* is missing, try each fallback.
    if not QFontDatabase.hasFamily(family):
        for candidate in fallback.replace("'", "").split(","):
            candidate = candidate.strip()
            if QFontDatabase.hasFamily(candidate):
                font.setFamily(candidate)
                break
    return font


# ---------------------------------------------------------------------------
# QSS stylesheet generation
# ---------------------------------------------------------------------------

def get_stylesheet(
    colors: ChiaColors = COLORS,
    font_size_delta: int = 0,
) -> str:
    """Return the complete QSS stylesheet as a single string.

    Parameters
    ----------
    colors:
        Colour palette to interpolate.  Defaults to the CHIA palette.
    font_size_delta:
        Integer offset (positive or negative) added to every
        font-size value for accessibility / user preference.

    Returns
    -------
    A multi-thousand-character QSS string ready for
    ``QApplication.setStyleSheet()``.
    """
    # Shorthand aliases keep the template readable.
    c = colors
    # Effective font sizes.
    fs = max(7, _BASE_UI_FONT_SIZE + font_size_delta)
    mfs = max(7, _BASE_MONO_FONT_SIZE + font_size_delta)
    # Slightly smaller secondary size for captions, hints, etc.
    sfs = max(7, fs - 1)

    return f"""
/* ===================================================================
   XOPTrader -- CHIA DEX Market-Maker Theme
   Generated by gui.theme.get_stylesheet()
   =================================================================== */

/* ----- Base window & widget backgrounds ----- */
QMainWindow {{
    background-color: {c.DARK_BG};
    color: {c.TEXT_PRIMARY};
    font-family: {_UI_FALLBACK};
    font-size: {fs}pt;
}}

QWidget {{
    background-color: {c.DARK_BG};
    color: {c.TEXT_PRIMARY};
    font-family: {_UI_FALLBACK};
    font-size: {fs}pt;
}}

/* ----- Menu bar ----- */
QMenuBar {{
    background-color: {c.PANEL_BG};
    color: {c.TEXT_PRIMARY};
    border-bottom: 1px solid {c.BORDER};
    padding: 2px 0px;
    font-size: {fs}pt;
}}

QMenuBar::item {{
    background: transparent;
    padding: 4px 10px;
}}

QMenuBar::item:selected {{
    background-color: {c.PRIMARY_GREEN};
    color: {c.DARK_BG};
    border-radius: 3px;
}}

/* ----- Drop-down menus ----- */
QMenu {{
    background-color: {c.PANEL_BG};
    color: {c.TEXT_PRIMARY};
    border: 1px solid {c.BORDER};
    padding: 4px 0px;
    font-size: {fs}pt;
}}

QMenu::item {{
    padding: 5px 28px 5px 20px;
}}

QMenu::item:selected {{
    background-color: {c.PRIMARY_GREEN};
    color: {c.DARK_BG};
}}

QMenu::separator {{
    height: 1px;
    background: {c.BORDER};
    margin: 4px 8px;
}}

/* ----- Toolbar ----- */
QToolBar {{
    background-color: {c.PANEL_BG};
    border: none;
    spacing: 4px;
    padding: 2px;
}}

QToolBar::separator {{
    width: 1px;
    background: {c.BORDER};
    margin: 4px 6px;
}}

/* ----- Push buttons ----- */
/* Default (dark) variant */
QPushButton {{
    background-color: {c.ELEVATED_BG};
    color: {c.TEXT_PRIMARY};
    border: 1px solid {c.BORDER};
    border-radius: 4px;
    padding: 5px 16px;
    font-size: {fs}pt;
    min-height: 20px;
}}

QPushButton:hover {{
    background-color: {c.PANEL_BG};
    border-color: {c.TEXT_SECONDARY};
}}

QPushButton:pressed {{
    background-color: {c.DARK_BG};
}}

QPushButton:disabled {{
    color: {c.TEXT_SECONDARY};
    background-color: {c.DARK_BG};
    border-color: {c.BORDER};
}}

/* Primary (green) variant -- assign objectName "primaryButton" */
QPushButton#primaryButton {{
    background-color: {c.PRIMARY_GREEN};
    color: {c.DARK_BG};
    border: 1px solid {c.LIGHT_GREEN};
    font-weight: 600;
}}

QPushButton#primaryButton:hover {{
    background-color: {c.LIGHT_GREEN};
}}

QPushButton#primaryButton:pressed {{
    background-color: {c.PRIMARY_GREEN};
}}

/* Danger (red) variant -- assign objectName "dangerButton" */
QPushButton#dangerButton {{
    background-color: {c.LOSS_RED};
    color: #ffffff;
    border: 1px solid {c.LOSS_RED};
    font-weight: 600;
}}

QPushButton#dangerButton:hover {{
    background-color: #FF6659;
}}

QPushButton#dangerButton:pressed {{
    background-color: #D32F2F;
}}

/* ----- Tab widget & tab bar ----- */
QTabWidget::pane {{
    background-color: {c.PANEL_BG};
    border: 1px solid {c.BORDER};
    border-top: none;
}}

QTabBar {{
    background: transparent;
}}

QTabBar::tab {{
    background-color: {c.DARK_BG};
    color: {c.TEXT_SECONDARY};
    border: 1px solid {c.BORDER};
    border-bottom: none;
    padding: 6px 18px;
    margin-right: 2px;
    border-top-left-radius: 4px;
    border-top-right-radius: 4px;
    font-size: {fs}pt;
}}

QTabBar::tab:selected {{
    background-color: {c.PANEL_BG};
    color: {c.TEXT_PRIMARY};
    border-bottom: 2px solid {c.PRIMARY_GREEN};
}}

QTabBar::tab:hover:!selected {{
    background-color: {c.ELEVATED_BG};
    color: {c.TEXT_PRIMARY};
}}

/* ----- Splitter handles ----- */
QSplitter::handle {{
    background-color: {c.BORDER};
}}

QSplitter::handle:horizontal {{
    width: 2px;
}}

QSplitter::handle:vertical {{
    height: 2px;
}}

/* ----- Tree / Table views ----- */
QTreeView, QTableView {{
    background-color: {c.PANEL_BG};
    alternate-background-color: {c.ELEVATED_BG};
    color: {c.TEXT_PRIMARY};
    border: 1px solid {c.BORDER};
    gridline-color: {c.BORDER};
    selection-background-color: {c.PRIMARY_GREEN};
    selection-color: {c.DARK_BG};
    font-family: {_MONO_FALLBACK};
    font-size: {mfs}pt;
}}

QTreeView::item, QTableView::item {{
    padding: 3px 6px;
}}

QTreeView::item:hover, QTableView::item:hover {{
    background-color: {c.ELEVATED_BG};
}}

QHeaderView {{
    background-color: {c.DARK_BG};
}}

QHeaderView::section {{
    background-color: {c.DARK_BG};
    color: {c.TEXT_SECONDARY};
    border: none;
    border-right: 1px solid {c.BORDER};
    border-bottom: 1px solid {c.BORDER};
    padding: 4px 8px;
    font-weight: 600;
    font-size: {sfs}pt;
}}

QHeaderView::section:hover {{
    color: {c.TEXT_PRIMARY};
}}

/* ----- Scroll bars (thin, unobtrusive) ----- */
QScrollBar:vertical {{
    background: {c.DARK_BG};
    width: 8px;
    margin: 0;
}}

QScrollBar::handle:vertical {{
    background: {c.BORDER};
    min-height: 30px;
    border-radius: 4px;
}}

QScrollBar::handle:vertical:hover {{
    background: {c.TEXT_SECONDARY};
}}

QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {{
    height: 0;
}}

QScrollBar:horizontal {{
    background: {c.DARK_BG};
    height: 8px;
    margin: 0;
}}

QScrollBar::handle:horizontal {{
    background: {c.BORDER};
    min-width: 30px;
    border-radius: 4px;
}}

QScrollBar::handle:horizontal:hover {{
    background: {c.TEXT_SECONDARY};
}}

QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {{
    width: 0;
}}

/* ----- Input fields ----- */
QLineEdit, QSpinBox, QDoubleSpinBox, QComboBox {{
    background-color: {c.ELEVATED_BG};
    color: {c.TEXT_PRIMARY};
    border: 1px solid {c.BORDER};
    border-radius: 4px;
    padding: 4px 8px;
    font-family: {_MONO_FALLBACK};
    font-size: {mfs}pt;
    selection-background-color: {c.PRIMARY_GREEN};
    selection-color: {c.DARK_BG};
}}

QLineEdit:focus, QSpinBox:focus, QDoubleSpinBox:focus, QComboBox:focus {{
    border-color: {c.PRIMARY_GREEN};
}}

QComboBox::drop-down {{
    border: none;
    width: 20px;
}}

QComboBox QAbstractItemView {{
    background-color: {c.PANEL_BG};
    color: {c.TEXT_PRIMARY};
    border: 1px solid {c.BORDER};
    selection-background-color: {c.PRIMARY_GREEN};
    selection-color: {c.DARK_BG};
}}

/* ----- Group box ----- */
QGroupBox {{
    border: 1px solid {c.BORDER};
    border-radius: 6px;
    margin-top: 12px;
    padding-top: 16px;
    font-size: {fs}pt;
}}

QGroupBox::title {{
    subcontrol-origin: margin;
    subcontrol-position: top left;
    padding: 0 6px;
    color: {c.PRIMARY_GREEN};
    font-weight: 600;
}}

/* ----- Labels ----- */
QLabel {{
    color: {c.TEXT_PRIMARY};
    background: transparent;
}}

/* ----- Status bar ----- */
QStatusBar {{
    background-color: {c.PANEL_BG};
    color: {c.TEXT_SECONDARY};
    border-top: 1px solid {c.BORDER};
    font-size: {sfs}pt;
}}

QStatusBar::item {{
    border: none;
}}

/* ----- Tooltips ----- */
QToolTip {{
    background-color: {c.PANEL_BG};
    color: {c.TEXT_PRIMARY};
    border: 1px solid {c.PRIMARY_GREEN};
    border-radius: 3px;
    padding: 4px 8px;
    font-size: {sfs}pt;
}}

/* ----- Progress bar ----- */
QProgressBar {{
    background-color: {c.ELEVATED_BG};
    border: 1px solid {c.BORDER};
    border-radius: 4px;
    text-align: center;
    color: {c.TEXT_PRIMARY};
    font-size: {sfs}pt;
    min-height: 16px;
}}

QProgressBar::chunk {{
    background-color: {c.PRIMARY_GREEN};
    border-radius: 3px;
}}

/* ----- Check box & radio button ----- */
QCheckBox, QRadioButton {{
    color: {c.TEXT_PRIMARY};
    spacing: 6px;
    font-size: {fs}pt;
}}

QCheckBox::indicator, QRadioButton::indicator {{
    width: 16px;
    height: 16px;
    border: 1px solid {c.BORDER};
    background-color: {c.ELEVATED_BG};
}}

QCheckBox::indicator {{
    border-radius: 3px;
}}

QRadioButton::indicator {{
    border-radius: 8px;
}}

QCheckBox::indicator:checked, QRadioButton::indicator:checked {{
    background-color: {c.PRIMARY_GREEN};
    border-color: {c.LIGHT_GREEN};
}}

QCheckBox::indicator:hover, QRadioButton::indicator:hover {{
    border-color: {c.PRIMARY_GREEN};
}}

/* ----- Slider ----- */
QSlider::groove:horizontal {{
    background: {c.ELEVATED_BG};
    height: 4px;
    border-radius: 2px;
}}

QSlider::handle:horizontal {{
    background: {c.PRIMARY_GREEN};
    width: 14px;
    height: 14px;
    margin: -5px 0;
    border-radius: 7px;
}}

QSlider::handle:horizontal:hover {{
    background: {c.LIGHT_GREEN};
}}

QSlider::groove:vertical {{
    background: {c.ELEVATED_BG};
    width: 4px;
    border-radius: 2px;
}}

QSlider::handle:vertical {{
    background: {c.PRIMARY_GREEN};
    width: 14px;
    height: 14px;
    margin: 0 -5px;
    border-radius: 7px;
}}

QSlider::handle:vertical:hover {{
    background: {c.LIGHT_GREEN};
}}
"""


# ---------------------------------------------------------------------------
# Theme application helper
# ---------------------------------------------------------------------------

def apply_theme(
    app: QApplication,
    font_size_delta: int = 0,
    colors: Optional[ChiaColors] = None,
) -> None:
    """Configure *app* with the CHIA dark theme.

    This sets the Fusion base style (consistent cross-platform look),
    applies the full QSS stylesheet, and installs the preferred fonts.

    Parameters
    ----------
    app:
        The running QApplication instance.
    font_size_delta:
        Point-size adjustment for accessibility.  ``+2`` makes all
        text two points larger; ``-1`` makes it one point smaller.
    colors:
        Optional custom colour palette.  Falls back to the default
        CHIA palette when *None*.
    """
    palette = colors if colors is not None else COLORS

    # Use Fusion style as the base -- it renders identically on every
    # platform and responds well to QSS overrides.
    app.setStyle("Fusion")

    # Resolve and apply fonts before the stylesheet so that QSS
    # font-family references match what the system actually provides.
    ui_font = _resolve_font(
        UI_FONT_FAMILY,
        _UI_FALLBACK,
        _BASE_UI_FONT_SIZE + font_size_delta,
    )
    app.setFont(ui_font)

    # Apply the complete stylesheet.
    app.setStyleSheet(get_stylesheet(palette, font_size_delta))
